/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2,the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#include <stdio.h>

/* Q1. 4백만을 넘는 때는 언제인가? */
void main()
{
	int num1 = 1;
    int num2 = 1;
    int num3 = 2;
	int cnt=0,sum=0;

	while(1)
	{
		if(num1>=4000000) break;
		printf("%d ", num1);
		if(num1%2==0)
			sum+=num1;
        num2 = num1+num3;
        num1 = num3;
        num3 = num2;
	}
	printf("\n%d\n",sum);
}